version: '3.8'

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:${LOCALSTACK_VERSION:-0.12.17.5}
    environment:
      - SERVICES=s3,dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOST_TMP_FOLDER=/tmp/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/tmp/localstack/data
    networks:
      - localstack-network

volumes:
  localstack-data:
    name: localstack-data

networks:
  localstack-network:
    name: localstack-network
